# Generated by Django 2.0 on 2019-05-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190527_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNun',
            new_name='ReadNum',
        ),
    ]
